language: node_js

node_js:
  - 10
  - 8

jobs:
  include:
    - stage: tests
      script: npm run test
    - stage: deploy
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: npm run build && npx semantic-release
