language: node_js

node_js:
  - 10
  - 8

jobs:
  include:
    - stage: tests
      script: npm run test
    - stage: build
      script: npm run build
    # Define the release stage that runs semantic-release
    - stage: deploy
      # Advanced: optionally overwrite your default `script` step to skip the tests
      skip_cleanup: true
      script: npm run build && npx semantic-release
